name: boggle_flutter
description: boggle_flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  auto_route: ^9.2.2
  intl: ^0.20.2
  bloc: ^9.0.0
  lottie: ^3.3.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_it: ^8.0.2
  injectable: ^2.4.4
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  analyzer: ^6.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^2.0.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  freezed: ^2.5.7

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
