name: boggle_flutter
description: boggle_flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  http: ^1.3.0
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1
  intl: ^0.20.2
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^2.0.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  auto_route_generator: ^10.0.1

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
